---
repos:
    - repo: git://github.com/ambv/black
      rev: 21.4b2
      hooks:
          - id: black
            language_version: python3.8

    - repo: git://github.com/timothycrosley/isort
      rev: 5.8.0
      hooks:
          - id: isort

    - repo: git://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
          - id: mypy
