name: BaSe
channels:
  - conda-forge
  - defaults
dependencies:
  - paramiko=2.7.1
  - pip=20.2.2
  - pyserial=3.4
  - pytest=6.1.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - pip:
    - signalslot==0.1.2
